- .github/workflows/ktlint-check.yml
- Github Action에 ktlint 자동 체크 기능 추가
- 앞으로 로컬에서 ktlintCheck 하고 ktlintFormat 하신 다음에 PR 올려주세요!
- ktlintFormat이 가끔 의도치 않은 동작을 할 때가 있다는 글을 봐서 작업 끝난 후 커밋 먼저 하시고 ktlintFormat 해서 자동 변경 사항을 직접 보는게 안전할것 같습니다.
> Style: main에 PR 올릴때 ktlintCheck 자동화

- .github/workflows/ktlint-check.yml
- github action 수정
- github market place에 있는 run ktlint with review dog 대신 gradlew ktlintCheck 사용
> Fix: Github Action ktlint 수정

- src/main/kotlin/com/wafflestudio/team03server/core/user/api/AuthController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/AuthService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/EmailService.kt
- 인증 이메일 전송 api /auth/sendVerificationEmail 
- 이메일 인증 확인 api /auth/checkEmailVerified
- 기존 userService -> authService로 이름 변경
- 로컬에서 테스트 완료했습니다.
- 회원가입, 로그인 관련 서비스는 authService로 추후 구현할 userService와 분리하기 위해 이름 변경하였습니다.
> Feat: 이메일 인증 관련 API

- .github/workflows/gradle.yml
- gradle.yml 파일 추가
- main 브랜치에 pr이 머지되면 바로 자동배포 액션이 실행됩니다. 빌드하는 데에 시간이 좀 걸려서 2-4분 정도 소요되었던 걸로 기억합니다. 자동배포가 실패하면 이메일이 옵니다.
- 저희가 사용하는 서버 환경에서 제대로 시뮬레이션을 해보지는 못했기 때문에 약간 뚝딱거리거나 잘 안 될 수도 있는데 에러가 생기는대로 바로바로 최대한 빠르게 수정해서 잘 작동할 수 있게 하겠습니다..!
- 현재 secrets에 관련 정보가 없어서 에러가 발생하는데 정보가 저장되는 대로 다시 작동 여부를 파악해야 할 것 같습니다.
> Docs: 자동배포 위한 gradle.yml 파일 추가

- src/main/kotlin/com/wafflestudio/team03server/config/WebConfig.kt
- CORS 에러 수정
- 프론트 분들 로컬에서 테스트가 용이하게 localhost:3000 임시 추가했습니다.
> Fix: CORS 에러 수정

- build.gradle.kts
- src/main/kotlin/com/wafflestudio/team03server/config/AwsConfig.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/TradePostController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/api/UserController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/S3Properties.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/S3Service.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/UserService.kt
- src/test/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostServiceTest.kt
- 프로필 이미지 업로드 API PUT /users/me/image
- 로컬에서 s3 업로드 테스트 완료하였습니다.
- 로컬에서 테스트 하려면 인텔리제이 상단 실행 버튼 왼쪽 눌러서 구성 편집 -> 옵션 수정 -> VM 옵션 추가에
- -Dcom.amazonaws.sdk.disableEc2Metadata=true 넣고 테스트하시면 됩니다.
- yml 파일은 dm으로 보내드릴게요
> Feat: 프로필 이미지 업로드 기능 구현

- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/NeighborController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/request/CreateNeighborCommentRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/request/CreateNeighborPostRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/request/UpdateNeighborCommentRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/request/UpdateNeighborPostRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/response/NeighborCommentResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/response/NeighborPostResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/entity/NeighborComment.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/entity/NeighborLike.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/entity/NeighborPost.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/repository/NeighborCommentRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/repository/NeighborLikeRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/repository/NeighborPostRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/service/NeighborCommentService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/service/NeighborPostService.kt
- 동네생활 게시판의 기본적인 기능인 글 생성, 조회, 수정, 삭제와 댓글 생성, 수정, 삭제를 구현했습니다.
- 동네생활 게시판을 위해 NeighborPost, NeighborComment, NeighborLike 엔티티가 추가되었습니다.
- 동네생활과 중고거래를 헷갈리지 않기 위해 Neighbor를 빠짐없이 붙였습니다..
- 각 기능 수정의 편의를 위해 글과 댓글 서비스를 분리하였습니다.
- 로컬에서 테스트 진행하였고 작동은 잘 됩니다. 테스트 코드는 코드 보완 과정에서 만들도록 하겠습니다.
- 좋아요 기능을 위한 테이블을 하나 만들었는데, 관련 함수가 '좋아요' 기능과 '좋아요 취소' 기능을 모두 담당해야 할지 이를 분리해야 할지 고민이 되어 일단 임시로 작성해두었습니다. 의견 부탁드립니다.
- 글을 조회할 때 댓글이 함께 조회되는데 댓글이 적은 상태에서는 불러오는 데에 큰 문제가 없지만 글과 댓글이 늘어나고 대댓글까지 생길 때는 시간이 오래 걸릴 것 같아서 추후 수정할 계획입니다.
- 중고거래 게시판과 동일한 방식이고 조회수는 일단 쿠키 확인 없이 볼 때마다 올라가는 방식으로 구현했습니다. 추후 다른 기능들을 구현하면서 보완하겠습니다.
- 급하게 한 터라 중간중간에 커밋을 못하고 한꺼번에 해버렸습니다.. 문제되는 점이 보이시면 언제든 코멘트 부탁드립니다.
> Feat: 동네생활 게시판 글 생성, 조회, 수정, 삭제 및 댓글 생성, 수정, 삭제

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/TradePostController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/entity/LikePost.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/entity/User.kt
- src/test/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostServiceTest.kt
- Like 연관관계 메서드를 작성하지 않았어서 이를 추가하고 테스트 코드 수정했습니다.
- proucts -> tradepost로 endpoint url 이름 변경했습니다.
-
-
> Fix: Like 연관관계 메서드 추가 및 테스트 추가

- build.gradle.kts
- src/main/kotlin/com/wafflestudio/team03server/config/QueryDslConfig.kt
- QueryDsl을 사용하기 위한 Config 설정했습니다.
- Build 진행해서 아래 스샷과 같이 QClass가 잘 생기는지 확인해보시고 사용하시면 될 것 같습니다.
> Feat: QueryDsl Config 설정

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/TradePostController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/response/PostResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/entity/LikePost.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/entity/TradePost.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/entity/TradePostImage.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/repository/TradePostImageRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/api/response/SimpleUserResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/entity/User.kt
- src/test/kotlin/com/wafflestudio/team03server/core/chat/service/ChatServiceTest.kt
- src/test/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostServiceTest.kt
- 중고거래 글에 이미지 올리는 기능 구현
-
- SImpleUserResponse에 imgUrl 필드를 추가하였는데 혹시 다르게 구현중이시라면 체크 부탁드립니다!
- 중고거래 글에 이미지파일 여러개를 올리는 부분 로컬테스트가 조금 까다롭네요ㅠ 혹시 팁이 있으시다면 공유 가능하실까요ㅠ
> Feat: 중고거래 글에 이미지 올리기 기능 구현

- src/main/kotlin/com/wafflestudio/team03server/config/WebConfig.kt
> Fix: cors 수정

- .github/workflows/gradle.yml
- .github/workflows/gradleTest.yml
- gradle.yml 살짝 수정해서 gradleTest.yml 생성하고 secret 추가 하였습니다.
- @Joanne19-drive 민지님 도커허브에 team3-test-server 레포 하나 만들어주실수 있으실까요?
- https://medium.com/daangn/deploy-%EB%B8%8C%EB%9E%9C%EC%B9%98-%EC%A0%84%EB%9E%B5-%ED%99%9C%EC%9A%A9-%EB%B0%A9%EB%B2%95-545f278ca878 
- 저희 dev 브랜치가 위 글의 deploy 브랜치 같은 역할이라고 생각하시면 될것 같습니다
> Docs: 테스트 서버 자동 배포용 gradleTest.yml 추가 및 gradle.yml 수정

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/ReviewController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/request/CreateReviewRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/ReviewService.kt
- RequestBody 어노테이션을 추가하였습니다.
- 추가하는 김에 score validation까지 추가하였습니다.
> Fix: 후기 생성 api 요청 body 못 받는 것 수정

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/response/ReviewResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/entity/Review.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/entity/ReviewerType.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/repository/ReviewCustomRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/repository/ReviewRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/ReviewService.kt
- 후기 조회 api 응답이 변경되었습니다.
- 후기 조회할때 리뷰어에 fetchjoin 적용하였습니다.
- 로컬 테스트 완료하였습니다.
- 일대다가 아니라 distinct 는 굳이 안걸어도 될것 같긴한데 일단 걸었습니다
> Fix: 후기 조회 api 응답 수정 및 fetch join 적용

- src/test/kotlin/com/wafflestudio/team03server/core/user/service/AuthServiceImplTest.kt
- src/test/kotlin/com/wafflestudio/team03server/core/user/service/UserServiceImplTest.kt
- authService 테스트 코드 작성
- 테스트 모두 정상적으로 완료되었습니다.
> Test: 회원가입, 로그인 테스트 코드

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/TradePostController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/response/PostPageResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/repository/TradePostRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/entity/SearchScope.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/entity/User.kt
- 중고거래 글 위치 기반 조회
- 로컬에서 테스트 하였습니다.
- 거리 기준은 일단 35km, 200km, 400km로 설정하였습니다.
> Feat: 중고거래 글 위치 기반 조회

- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/api/NeighborController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/repository/NeighborPostRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/neighbor/service/NeighborPostService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- src/main/kotlin/com/wafflestudio/team03server/utils/QueryUtil.kt
- 동네생활 글 위치 기반 조회
- 로컬에서 잘 작동 합니다.
- 네이티브 쿼리 키워드를 얻는 부분이 중복되어서 유틸 클래스로 리팩토링 했습니다.
> Feat: 동네생활 글 위치 기반 조회

- src/main/kotlin/com/wafflestudio/team03server/core/user/api/UserController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/api/request/EditSearchScopeRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/UserService.kt
- PATCH /users/me/search-scope
- 로컬 테스트 완료하였습니다.
> Feat: 글 검색 범위 설정 api 구현

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/response/PostPageResponse.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/repository/TradePostRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- total 값을 가져오도록 쿼리 추가
- 중고거래 글 조회 테스트 다시 잘 작동합니다.
> Fix: PagingResponse.total 값 수정

- src/test/kotlin/com/wafflestudio/team03server/core/neighbor/service/NeighborPostServiceTest.kt
- 동네생활 테스트 깨지는 것 수정
- 동네생활 테스트 모두 정상 작동합니다.
> Fix: 동네생활 테스트 깨지는 것 수정

- src/main/kotlin/com/wafflestudio/team03server/common/ExceptionHandler.kt
- 프론트에서 받기 편한도록 에러 메세지를 하나씩만 내려주는 것으로 통일하였습니다.
> Fix: 에러 메세지 하나씩만 내려주는것으로 수정

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/TradePostController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/repository/TradePostRepository.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- 거래 가능한 글만 보는 기능을 추가하였습니다
- 로컬에서 테스트 완료하였습니다
> Feat: 거래 가능한 글만 보기 기능 추가

- src/main/kotlin/com/wafflestudio/team03server/core/user/api/request/EditLocationRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/api/request/SignUpRequest.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/AuthService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/service/UserService.kt
- src/test/kotlin/com/wafflestudio/team03server/core/user/service/UserServiceImplTest.kt
- 주소 변경시 좌표 정보도 함께 받도록 구현하였습니다.
- 로컬에서 테스트 하였습니다
> Fix: 주소 변경 요청에 좌표 정보 포함

- src/main/kotlin/com/wafflestudio/team03server/core/trade/api/TradePostController.kt
- src/main/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostService.kt
- src/main/kotlin/com/wafflestudio/team03server/core/user/repository/UserRepository.kt
- src/test/kotlin/com/wafflestudio/team03server/core/trade/service/TradePostServiceTest.kt
- 전국 기준 따뜻한 사람 순위를 추가했습니다.
- 로컬에서 테스트 완료했습니다.
- 일단 전국 기준으로 정한 것 같아서 그대로 구현했는데 이후 수정이 생기면 처리하겠습니다.
> Feat: 전국 기준 따뜻한 사람 순위

- src/main/kotlin/com/wafflestudio/team03server/core/user/api/response/UserResponse.kt
- 유저 정보 내려줄때 searchScope 필드 추가
> Fix: 유저 프로필 응답에 검색 범위 추가
